// <auto-generated />
using System;
using Demo128___EFCore.DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo128___EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240507051832_SeedBooksData")]
    partial class SeedBooksData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksAuthors", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BooksAuthors");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ISBN = "B12345_1",
                            Title = "کتاب شماره 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ISBN = "B12345_2",
                            Title = "کتاب شماره 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ISBN = "B12345_3",
                            Title = "کتاب شماره 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ISBN = "B12345_4",
                            Title = "کتاب شماره 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ISBN = "B12345_5",
                            Title = "کتاب شماره 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ISBN = "B12345_6",
                            Title = "کتاب شماره 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ISBN = "B12345_7",
                            Title = "کتاب شماره 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ISBN = "B12345_8",
                            Title = "کتاب شماره 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ISBN = "B12345_9",
                            Title = "کتاب شماره 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ISBN = "B12345_10",
                            Title = "کتاب شماره 10"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ISBN = "B12345_11",
                            Title = "کتاب شماره 11"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ISBN = "B12345_12",
                            Title = "کتاب شماره 12"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            ISBN = "B12345_13",
                            Title = "کتاب شماره 13"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            ISBN = "B12345_14",
                            Title = "کتاب شماره 14"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            ISBN = "B12345_15",
                            Title = "کتاب شماره 15"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            ISBN = "B12345_16",
                            Title = "کتاب شماره 16"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            ISBN = "B12345_17",
                            Title = "کتاب شماره 17"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            ISBN = "B12345_18",
                            Title = "کتاب شماره 18"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            ISBN = "B12345_19",
                            Title = "کتاب شماره 19"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            ISBN = "B12345_20",
                            Title = "کتاب شماره 20"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            ISBN = "B12345_21",
                            Title = "کتاب شماره 21"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            ISBN = "B12345_22",
                            Title = "کتاب شماره 22"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            ISBN = "B12345_23",
                            Title = "کتاب شماره 23"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            ISBN = "B12345_24",
                            Title = "کتاب شماره 24"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            ISBN = "B12345_25",
                            Title = "کتاب شماره 25"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            ISBN = "B12345_26",
                            Title = "کتاب شماره 26"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            ISBN = "B12345_27",
                            Title = "کتاب شماره 27"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            ISBN = "B12345_28",
                            Title = "کتاب شماره 28"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            ISBN = "B12345_29",
                            Title = "کتاب شماره 29"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            ISBN = "B12345_30",
                            Title = "کتاب شماره 30"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            ISBN = "B12345_31",
                            Title = "کتاب شماره 31"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            ISBN = "B12345_32",
                            Title = "کتاب شماره 32"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            ISBN = "B12345_33",
                            Title = "کتاب شماره 33"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            ISBN = "B12345_34",
                            Title = "کتاب شماره 34"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            ISBN = "B12345_35",
                            Title = "کتاب شماره 35"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            ISBN = "B12345_36",
                            Title = "کتاب شماره 36"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            ISBN = "B12345_37",
                            Title = "کتاب شماره 37"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            ISBN = "B12345_38",
                            Title = "کتاب شماره 38"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            ISBN = "B12345_39",
                            Title = "کتاب شماره 39"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            ISBN = "B12345_40",
                            Title = "کتاب شماره 40"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            ISBN = "B12345_41",
                            Title = "کتاب شماره 41"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 1,
                            ISBN = "B12345_42",
                            Title = "کتاب شماره 42"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            ISBN = "B12345_43",
                            Title = "کتاب شماره 43"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 1,
                            ISBN = "B12345_44",
                            Title = "کتاب شماره 44"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            ISBN = "B12345_45",
                            Title = "کتاب شماره 45"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            ISBN = "B12345_46",
                            Title = "کتاب شماره 46"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            ISBN = "B12345_47",
                            Title = "کتاب شماره 47"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            ISBN = "B12345_48",
                            Title = "کتاب شماره 48"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            ISBN = "B12345_49",
                            Title = "کتاب شماره 49"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            ISBN = "B12345_50",
                            Title = "کتاب شماره 50"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 1,
                            ISBN = "B12345_51",
                            Title = "کتاب شماره 51"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            ISBN = "B12345_52",
                            Title = "کتاب شماره 52"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            ISBN = "B12345_53",
                            Title = "کتاب شماره 53"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 1,
                            ISBN = "B12345_54",
                            Title = "کتاب شماره 54"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 1,
                            ISBN = "B12345_55",
                            Title = "کتاب شماره 55"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 1,
                            ISBN = "B12345_56",
                            Title = "کتاب شماره 56"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 1,
                            ISBN = "B12345_57",
                            Title = "کتاب شماره 57"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 1,
                            ISBN = "B12345_58",
                            Title = "کتاب شماره 58"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 1,
                            ISBN = "B12345_59",
                            Title = "کتاب شماره 59"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            ISBN = "B12345_60",
                            Title = "کتاب شماره 60"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 1,
                            ISBN = "B12345_61",
                            Title = "کتاب شماره 61"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 1,
                            ISBN = "B12345_62",
                            Title = "کتاب شماره 62"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 1,
                            ISBN = "B12345_63",
                            Title = "کتاب شماره 63"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 1,
                            ISBN = "B12345_64",
                            Title = "کتاب شماره 64"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 1,
                            ISBN = "B12345_65",
                            Title = "کتاب شماره 65"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 1,
                            ISBN = "B12345_66",
                            Title = "کتاب شماره 66"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 1,
                            ISBN = "B12345_67",
                            Title = "کتاب شماره 67"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            ISBN = "B12345_68",
                            Title = "کتاب شماره 68"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 1,
                            ISBN = "B12345_69",
                            Title = "کتاب شماره 69"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 1,
                            ISBN = "B12345_70",
                            Title = "کتاب شماره 70"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 1,
                            ISBN = "B12345_71",
                            Title = "کتاب شماره 71"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 1,
                            ISBN = "B12345_72",
                            Title = "کتاب شماره 72"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 1,
                            ISBN = "B12345_73",
                            Title = "کتاب شماره 73"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 1,
                            ISBN = "B12345_74",
                            Title = "کتاب شماره 74"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 1,
                            ISBN = "B12345_75",
                            Title = "کتاب شماره 75"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            ISBN = "B12345_76",
                            Title = "کتاب شماره 76"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 1,
                            ISBN = "B12345_77",
                            Title = "کتاب شماره 77"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 1,
                            ISBN = "B12345_78",
                            Title = "کتاب شماره 78"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 1,
                            ISBN = "B12345_79",
                            Title = "کتاب شماره 79"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            ISBN = "B12345_80",
                            Title = "کتاب شماره 80"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 1,
                            ISBN = "B12345_81",
                            Title = "کتاب شماره 81"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 1,
                            ISBN = "B12345_82",
                            Title = "کتاب شماره 82"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 1,
                            ISBN = "B12345_83",
                            Title = "کتاب شماره 83"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 1,
                            ISBN = "B12345_84",
                            Title = "کتاب شماره 84"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 1,
                            ISBN = "B12345_85",
                            Title = "کتاب شماره 85"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 1,
                            ISBN = "B12345_86",
                            Title = "کتاب شماره 86"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 1,
                            ISBN = "B12345_87",
                            Title = "کتاب شماره 87"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 1,
                            ISBN = "B12345_88",
                            Title = "کتاب شماره 88"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 1,
                            ISBN = "B12345_89",
                            Title = "کتاب شماره 89"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 1,
                            ISBN = "B12345_90",
                            Title = "کتاب شماره 90"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 1,
                            ISBN = "B12345_91",
                            Title = "کتاب شماره 91"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 1,
                            ISBN = "B12345_92",
                            Title = "کتاب شماره 92"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 1,
                            ISBN = "B12345_93",
                            Title = "کتاب شماره 93"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 1,
                            ISBN = "B12345_94",
                            Title = "کتاب شماره 94"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 1,
                            ISBN = "B12345_95",
                            Title = "کتاب شماره 95"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 1,
                            ISBN = "B12345_96",
                            Title = "کتاب شماره 96"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 1,
                            ISBN = "B12345_97",
                            Title = "کتاب شماره 97"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 1,
                            ISBN = "B12345_98",
                            Title = "کتاب شماره 98"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 1,
                            ISBN = "B12345_99",
                            Title = "کتاب شماره 99"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            ISBN = "B12345_100",
                            Title = "کتاب شماره 100"
                        });
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.BookCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "کتاب های داستانی"
                        });
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[Firstname] + ' ' + [Lastname]");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.MemberAddress", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MemberId");

                    b.ToTable("MembersAddresses", (string)null);
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disabled = false,
                            Password = "123456",
                            RegisterDate = new DateTime(2024, 5, 7, 8, 48, 32, 678, DateTimeKind.Local).AddTicks(9085),
                            Role = "sysadmin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BooksAuthors", b =>
                {
                    b.HasOne("Demo128___EFCore.DbModel.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo128___EFCore.DbModel.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.Book", b =>
                {
                    b.HasOne("Demo128___EFCore.DbModel.Entities.BookCategory", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.MemberAddress", b =>
                {
                    b.HasOne("Demo128___EFCore.DbModel.Entities.Member", "Member")
                        .WithOne("MemberAddress")
                        .HasForeignKey("Demo128___EFCore.DbModel.Entities.MemberAddress", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Demo128___EFCore.DbModel.Entities.Member", b =>
                {
                    b.Navigation("MemberAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
